function filterGUI()
  filterHandle=[];
  %Tmp
  load('/tmp/myhnadles.mat');
  
  
  myhandles=getappdata(0,'myhandles');

  
  groupList = fieldnames(myhandles.grouped_metadata{1});
  %Skip the first field which is always files_in_group
  groupList = groupList(2:end);

  % color_scale=zeros(number_of_markers,2);
  % color_scale(:,1)=min_intensity;
  % color_scale(:,2)=max_intensity;
  color_scale=myhandles.marker_scales;
  color_order=myhandles.color_order;
  colors=myhandles.display_colors;
  %colors=color_order(1:number_of_markers);

  gui_width=600;
  gui_height=700;
  background_color='black';
  foreground_color='white';
  panel_width=1;
  panel_height=0.05;
  
  mainFig=figure('position',[0,0,gui_width,gui_height],'Color',background_color,...
    'MenuBar','none');
  
  filterHandle.filter{1}.filterPanel= uipanel('Parent', mainFig, ...
            'Position', [0 .8 panel_width panel_height],...
            'BackgroundColor', 'black',...
            'Tag', 'userconsole');     
          
          
   %createFilterPanel(handles.filterPanel,groupList, myhandles.grouped_metadata);
   createFilterPanel(filterHandle.filter{1}.filterPanel, groupList, myhandles.grouped_metadata,1,1)
   
   
  function createAllFilterPanel()
    
  end
  
  function createFilterPanel(parentPanel, groupList, groupedMetadata,filterNr,selectedGroup)
    filterHandle.filter{filterNr}.filterType=uicontrol('Parent', parentPanel, 'Style', 'popup',...
           'String', 'And|Or', ...
           'Units', 'normalized', 'FontWeight', 'bold',...
           'BackgroundColor', [1 1 1], 'Position', [0.02 0 0.1 0.9]);
    filterHandle.filter{filterNr}.GroupList=uicontrol('Parent', parentPanel, 'Style', 'popup',...
           'String', groupList, ...
           'Units', 'normalized', 'FontWeight', 'bold',...
           'BackgroundColor', [1 1 1], 'Position', [0.18 0 0.30 0.9],...
           'Callback', {@groupListCallBack, filterNr,groupedMetadata});           
    filterHandle.filter{filterNr}.GroupOperator=uicontrol('Parent', parentPanel, 'Style', 'popup',...
           'String', '=|!=', ...
           'Units', 'normalized', 'FontWeight', 'bold',...
           'BackgroundColor', [1 1 1], 'Position', [0.49 0 0.05 0.9]);    
    groupFields=cellfun(@(x) cell2mat(getfield(x,groupList{selectedGroup})),...
                groupedMetadata,'UniformOutput',false);
    filterHandle.filter{filterNr}.GroupFields=uicontrol('Parent', parentPanel, 'Style', 'popup',...
           'String', groupFields, ...
           'Units', 'normalized', 'FontWeight', 'bold',...
           'BackgroundColor', [1 1 1], 'Position', [0.55 0 0.30 0.9]);
    filterHandle.filter{filterNr}.RemoveBtn=uicontrol('Parent', parentPanel, 'Style', 'pushbutton',...
           'String', 'Remove', ...
           'Units', 'normalized', 'FontWeight', 'bold',...
           'BackgroundColor', [1 1 1], 'Position', [0.86 0.1 0.13 0.8]);
  end


  function groupListCallBack(src, evt, filterNr,groupedMetadata)
    groupFilter=filterHandle.filter{filterNr};
    groupIndex=get(groupFilter.GroupList, 'Value');
    groupFields=cellfun(@(x) cell2mat(getfield(x,groupList{groupIndex})),...
                groupedMetadata,'UniformOutput',false);
    filterHandle.filter{filterNr}.GroupFields=uicontrol('Parent',...
            filterHandle.filter{filterNr}.filterPanel, 'Style', 'popup',...
           'String', groupFields, ...
           'Units', 'normalized', 'FontWeight', 'bold',...
           'BackgroundColor', [1 1 1], 'Position', [0.55 0 0.30 0.9]);
  end

end